services: 
  live_data_generator:
    build:
      context: .
      dockerfile: python_caller.dockerfile
    depends_on: # it will wait for mongoDB to be running
      - mongoDB
  mongoDB:
    image: mongo:7
    container_name: sentinel-mongodb
    restart: always
    ports:
      - "27017:27017"
    # volumes: 
    #   - mongodb_data:/data/db
    command: ["--replSet", "rs0"]  # initiliase a replica set
  mongo-init:
    build:
      context: .
      dockerfile: mongo_init.dockerfile
    depends_on:
      - mongoDB
    restart: "no"
  mongo-listener:
    build:
      context: .
      dockerfile: listener_caller.dockerfile
    depends_on:
      - mongoDB

  redis:
    image: redis:7
    container_name: sentinel-redis
    restart: always
    ports:
      - "6379:6379" 
  qdrant:
    image: qdrant/qdrant
    container_name: sentinel-qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes: 
      - qdrant_data:/qdrant/storage

volumes: 
  #mongodb_data:
  qdrant_data:
  ollama_data:
